login: &login
  adapter: mysql2
  username: chnzgapplpcopd
  password: _AnxPxE3ThBA7jgA7fpxqdN2e0
  database: dcf5jgoc74d7i0
  host: "ec2-54-243-231-119.compute-1.amazonaws.com"

development: &development
  <<: *login

test: &test
  <<: *login

production: &production
  <<: *login
